const UPDATE_DATA = "UPDATE_DATA";
const UPDATE_FILTER_INPUT = "UPDATE_FILTER_INPUT";
const CLEAR_FILTER_INPUT = "CLEAR_FILTER_INPUT";
const ADD_FILTER = "ADD_FILTER";
const DELETE_FILTER = "DELETE_FILTER";
const DELETE_ALL_FILTERS = "DELETE_ALL_FILTERS";
const CHANGE_SORT = "CHANGE_SORT";
const LOAD_TOGGLE = "LOAD_TOGGLE";

export {
UPDATE_DATA,
UPDATE_FILTER_INPUT,
CLEAR_FILTER_INPUT,
ADD_FILTER,
DELETE_FILTER,
DELETE_ALL_FILTERS,
CHANGE_SORT,
LOAD_TOGGLE
};
